/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesaje.data;

import Controladores.ClienteController;
import Controladores.ConductorController;
import Controladores.ConexionPuertoController;
import Controladores.ProductoController;
import Controladores.OperacionController;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import pesaje.data.Conductor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import panamahitek.Arduino.PanamaHitek_Arduino;
import jssc.*;
import pesaje.data.DbUtils;


/**
 *
 * @author Hyrex
 */
public class MainMenu extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    PanamaHitek_Arduino arduino = new PanamaHitek_Arduino();
      SerialPortEventListener evento = new SerialPortEventListener() {

        @Override
        public void serialEvent(SerialPortEvent spe) {
            
            
            try{
//                if(arduino.isMessageAvailable()){
                txt_peso.setText(String.valueOf(arduino.receiveData()));    
                System.out.println(arduino.receiveData());
//                }
//                }
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null,ex + "Error al leer los datos");
            }

        }
    };
    
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        conn=db.java_db();
        initComponents(); 
        
        try {
            arduino.arduinoRXTX("COM3", 9600,evento);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex + " fallo al conectar");
        }
        
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
     
        ClienteController cliente = new ClienteController();
        ProductoController producto = new ProductoController();
        ConductorController conductor = new ConductorController();
        conductor.mostrarConductores(cmo_conductor);
        cliente.mostrarClientes(cmo_cliente);
        producto.mostrarProductor(cmo_producto);
        AutoCompleteDecorator.decorate(cmo_cliente);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmo_cliente = new javax.swing.JComboBox<>();
        cmo_producto = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txt_peso = new javax.swing.JFormattedTextField();
        cmo_conductor = new javax.swing.JComboBox<>();
        cmd_addcliente = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesaje/imgenes/layers_32x28.png"))); // NOI18N
        jButton1.setText("Productos");
        jButton1.setToolTipText("Gestión de productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 460, 160, 60);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesaje/imgenes/logout.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(750, 10, 40, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesaje/imgenes/Add.png"))); // NOI18N
        jButton2.setText("Clientes");
        jButton2.setToolTipText("Gestión de clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(610, 460, 160, 60);

        cmo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmo_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(cmo_cliente);
        cmo_cliente.setBounds(220, 420, 130, 30);

        jPanel1.add(cmo_producto);
        cmo_producto.setBounds(360, 420, 130, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Peso de vehiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        txt_peso.setEditable(false);
        txt_peso.setBackground(new java.awt.Color(0, 0, 0));
        txt_peso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        txt_peso.setForeground(new java.awt.Color(51, 255, 51));
        txt_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txt_peso.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txt_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 70, 450, 210);

        jPanel1.add(cmo_conductor);
        cmo_conductor.setBounds(40, 420, 130, 30);

        cmd_addcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesaje/imgenes/plus_alt_32x32.png"))); // NOI18N
        cmd_addcliente.setToolTipText("Adicionar conductor");
        cmd_addcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addclienteActionPerformed(evt);
            }
        });
        jPanel1.add(cmd_addcliente);
        cmd_addcliente.setBounds(170, 420, 40, 31);

        cmd_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesaje/imgenes/check_alt_32x32.png"))); // NOI18N
        cmd_save.setToolTipText("");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });
        jPanel1.add(cmd_save);
        cmd_save.setBounds(240, 310, 70, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Productos");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 400, 80, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Conductor");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 400, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Clientes");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 400, 80, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ingreso placa");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 290, 80, 15);

        txt_placa.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPanel1.add(txt_placa);
        txt_placa.setBounds(40, 310, 190, 80);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 530);

        jMenu1.setText("Configuración");

        jMenuItem1.setText("Auditoria");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
                   Audit_details j = new Audit_details();
                   j.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                  Usuarios j = new Usuarios();
                   j.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Login j = new Login();
        j.setVisible(true);
        this.dispose();

        try{
            Date currentDate = GregorianCalendar.getInstance().getTime();
            DateFormat df = DateFormat.getDateInstance();
            String dateString = df.format(currentDate);

            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            String timeString = sdf.format(d);

            String value0 = timeString;
            String values = dateString;
            
            int value = Emp.empId;
            String reg = "insert into Audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+values+"','Logged out')";
            pst=conn.prepareStatement(reg);
            pst.execute();
            this.dispose();
        }catch (Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
        finally {

            try{
                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Productos p= new Productos();
        p.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cliente cl = new Cliente(); 
        cl.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesoActionPerformed

    private void cmo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmo_clienteActionPerformed

    private void cmd_addclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addclienteActionPerformed
        
        Conductor con = new Conductor();
        
//        con.setIconifiable(true);
//        con.setMaximizable(false);
//        con.toFront();
        con.setVisible(true);
    }//GEN-LAST:event_cmd_addclienteActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, cmo_conductor.getItemAt(cmo_conductor.getSelectedIndex()).getId());
        
        
        if(txt_placa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por favor la placa es necesaria para el ingreso");
            return;
        }
        
        Float peso = Float.parseFloat(txt_peso.getText());
        if(peso <= 0.00){
            JOptionPane.showMessageDialog(null,"Peso invalido para el ingreso");
            return;
        }
        
        if(String.valueOf(cmo_cliente.getSelectedItem()).isEmpty()){
            JOptionPane.showMessageDialog(null,"Cliente invalido");
            return;
        }
        
        if(String.valueOf(cmo_producto.getSelectedItem()).isEmpty() ){
            JOptionPane.showMessageDialog(null,"Producto invalido");
            return;
        }
        
        if(String.valueOf(cmo_conductor.getSelectedItem()).isEmpty()){
            JOptionPane.showMessageDialog(null,"Conductor invalido");
            return;
        }
        
        int conductor = Integer.parseInt(cmo_conductor.getItemAt(cmo_conductor.getSelectedIndex()).getId());
        int cliente   = Integer.parseInt(cmo_cliente.getItemAt(cmo_cliente.getSelectedIndex()).getId());
        int producto  = Integer.parseInt(cmo_producto.getItemAt(cmo_producto.getSelectedIndex()).getId());
        String placa = txt_placa.getText();
        
        OperacionController operaciones = new OperacionController();
        
        if (operaciones.verificarVehiculo(placa).equals("E")) {
            int accion = JOptionPane.showConfirmDialog(null,"¿La placa " + placa + " se encuentra en la trilladora desea darle salida?",
                                          "Salida vehiculo",JOptionPane.YES_NO_OPTION);
            
            if (accion == 0) {
               operaciones.salidaVehiculo(placa, peso);
               this.txt_placa.setText("");
            }
            
        }else{
            operaciones.ingresoVehiculo(placa, peso, cliente, conductor, producto);
            this.txt_placa.setText("");
        }
        
        
    }//GEN-LAST:event_cmd_saveActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_addcliente;
    private javax.swing.JButton cmd_save;
    public static javax.swing.JComboBox<ClienteController> cmo_cliente;
    public static javax.swing.JComboBox<ConductorController> cmo_conductor;
    public static javax.swing.JComboBox<ProductoController> cmo_producto;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txt_peso;
    private javax.swing.JTextField txt_placa;
    // End of variables declaration//GEN-END:variables

    
}
